### ISSUE TITLE
-ffast-math gcc flag has large performance hit

### ISSUE THREAD

**Issue by sabauma** [zaxtax/naive_bayes#2]
The `-ffast-math` option adds a 1.4x overhead to the generated C code for a small benchmark

    gcc -Ofast
    C,10,10,100,1,23.590057689

    gcc -O3
    C,10,10,100,1,16.332357235

I've tracked the hit down to one of the optimizations enabled by `-ffast-math`
that is not `-funsafe-math-optimizations`. The performance hit is unfortunate,
but I'm concerned that the difference may be due to precision differences.

**Comment by sabauma** [comment]
The `-Ofast` option is the default used in the Makefile

**Comment by zaxtax** [comment]
How can precision issues cause a slowdown? I'm OK changing it to -O3

**Comment by sabauma** [comment]
If the algorithm is iterating until convergence, then precision may effect how many iterations are needed. I don't know what kind of ranges are expected of the floating point values in this example, but denormalization might be cropping up as well.

**Comment by zaxtax** [comment]
Well the current code does just one iteration. So there are some concerns
about precision from a correctness standpoint. I'm just surprised it would
effect runtime.

**Comment by sabauma** [comment]
The overhead seems to be due to a function calls to the builtin `log` function being replaced by `__log_finite`. I'm not sure why this would be slower unless the program is generating NaNs/Infinities resulting in different behaviour. Is there an easy way to validate the output of each version of the program?
