### ISSUE TITLE
Missing data files for Main.hs

### ISSUE THREAD

**Issue by sabauma** [zaxtax/naive_bayes#3]
The Main.hs file for the hand written example lacks the corresponding data file from `"/home/zv/datasets/20_newsgroups"`, which is currently hard coded.

**Comment by zaxtax** [comment]
That data file would be
http://qwone.com/~jason/20Newsgroups/20news-19997.tar.gz

I didn't think it was good to include in the repo. One thing I was thinking
is to have a
command to download it to a standard place and remove the hardcoded
directory.

**Comment by sabauma** [comment]
Cool. I just wanted the data so I can have a baseline for performance comparisons.  I added a download script that will pull the tarball and unpack into the repo. Main.hs now pulls data from "./20_newsgroups", so remember to run `download.sh` first.

**Comment by zaxtax** [comment]
We can make the data file a dependency in the makefile.
